
# Load a single session
Session:
  animal: 'CaP28'
  date: '092519'                # for single day analysis
  dates: ['070121, 071621']     # iterate for multi-day analysis

Directory:
  data : 'C:\Users\flynn\repos\CalciumAnalysis\datasets'
  statsave: './Desktop'
  plotsave: 'C:\Users\dilorenzo\Desktop\CalciumPlots\'

# Names used in pattern matching to distinguish files
Filenames:
  traces: 'traces3'
  events: 'processed'
  eating: 'Scored2'
  gpio: 'gpio.csv'

# Map event names to color for graphing
Colors:
    Chocolate : saddlebrown
    Peanut : darkorange
    NaCl : green
    Sucrose : purple
    Acid : yellow
    Quinine : red
    Rinse : lightsteelblue
    Lick : darkgray
    Approach : pink
    Eating: blue
    Grooming: cyan
    Entry: lime
    Doing Nothing: k


# For GPIO ports 1-4. Value indicates GPIO number.
Decoder:
    Rinse : [1, 2, 3, 4]
    ArtSal : [1, 3, 4]
    Quinine : [1, 2, 4]
    NaCl : [1, 3]
    Sucrose : [1, 2]
    MSG : [1, 4]
    Citric : [1, 2, 3]

# For Plots.
Plots:
  # FFMPEG is used for interactive / 3d plots. For guide on downloading:
  # https://stackoverflow.com/questions/13316397/matplotlib-animation-no-moviewriters-available
  # https://suryadayn.medium.com/error-requested-moviewriter-ffmpeg-not-available-easy-fix-9d1890a487d3
  # download from: https://ffmpeg.org/download.html
  FFMPEG : 'C:\ProgramData\Anaconda3\envs\cax\Library\bin\ffmpeg'


