
# Load a single session
Session:
  animal: 'PGT13'
  date: '030322'                # for single day analysis
  dates: ['070121, 071621']     # iterate for multi-day analysis

Directory:
  # data : '/Users/flynnoconnell/Documents/repos/canalysis/datasets'
  data: '/Users/flynnoconnell/Dropbox/Lab/Calcium_Imaging/Data'
  statsave: 'Users/flynnoconnell/Dropbox/Lab/Calcium_Imaging/CalciumImages'
  plotsave: 'Users/flynnoconnell/Dropbox/Lab/Calcium_Imaging/CalciumImages'

# Names used in pattern matching to distinguish files
Filenames:
  traces: 'PGT13_030322_ROI_traces_allcells'
  events: 'processed'
  eating: 'Scored1'
  gpio: 'gpio.csv'
  adjust: 34 # time to adjust for eating events
  doeating: False
  doevents: True


# Map event names to color for graphing
Colors:
    Chocolate : saddlebrown
    Lick : gray
    Peanut  : darkorange
    NaCl : darkgreen
    Sucrose : purple
    MSG : orange
    Citric : yellow
    ArtSal : darkblue
    Acid : yellow
    Quinine : red
    Approach : pink
    Grooming: cyan
    Entry: lime
    Acquisition: orange
    FrontLeft: lime
    FrontRight: lime
    BackLeft: lime
    BackRight: lime
    Eating: blue
    Quiescent: black
    Rinse: blue
    Interval: k

# For GPIO ports 1-4. Value indicates GPIO number.
Decoder:
    Rinse : [1, 2, 3, 4]
    ArtSal : [1, 3, 4]
    Quinine : [1, 2, 4]
    NaCl : [1, 3]
    Sucrose : [1, 2]
    MSG : [1, 4]
    Citric : [1, 2, 3]


Plots:
  # FFMPEG is used for interactive / 3d plots. For guide on downloading:
  # https://stackoverflow.com/questions/13316397/matplotlib-animation-no-moviewriters-available
  # https://suryadayn.medium.com/error-requested-moviewriter-ffmpeg-not-available-easy-fix-9d1890a487d3
  # download from: https://ffmpeg.org/download.html
  FFMPEG : 'Users/flynnoconnell/miniconda3/envs/caiman/bin/ffmpeg'


